=== DavidRodriguezLeiras/LXMI/UD4/409_Baloncesto - Hecho/baloncesto.dtd
<!ELEMENT equipos_baloncesto (equipo)*>
<!ELEMENT equipo (nombre,ciudad,entrenador,jugador)>
<!ELEMENT jugador (nombre,posicion,nacionalidad)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT entrenador (#PCDATA)>
<!ELEMENT posicion (#PCDATA)>
<!ELEMENT nacionalidad (#PCDATA)>
<!ATTLIST posicion posicion (Base|Escolta|Alero|Pivot) #REQUIRED>

=== DavidRodriguezLeiras/LXMI/Ejercicios UD4/tarea recopilatorio/409_Baloncesto - Hecho/baloncesto.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE equipos_baloncesto SYSTEM "baloncesto.dtd">
<equipos_baloncesto>
    <equipo>
        <nombre></nombre>
        <ciudad></ciudad>
        <entrenador></entrenador>
        <jugador>
            <nombre></nombre>
            <posicion posicion="Alero"></posicion>
            <nacionalidad></nacionalidad>
        </jugador>
    </equipo>
    <equipo>
        <nombre></nombre>
        <ciudad></ciudad>
        <entrenador></entrenador>
        <jugador>
            <nombre></nombre>
            <posicion posicion="Alero"></posicion>
            <nacionalidad></nacionalidad>
        </jugador>
    </equipo>
</equipos_baloncesto>
