=== DavidRodriguezLeiras/LXMI/UD4/405_Autopista - Hecho/paneles.dtd
<!ELEMENT paneles (evento)*>
<!ELEMENT evento (via,pk,retencion,sentido,carrilescortados?)>
<!ELEMENT via (nombre,ref,origen,destino,(doble|sentido),carriles)>
<!ELEMENT pk (#PCDATA)>
<!ELEMENT retencion (#PCDATA)>
<!ELEMENT carrilescortados (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT ref (#PCDATA)>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT destino (#PCDATA)>
<!ELEMENT doble EMPTY>
<!ELEMENT sentido (#PCDATA)>
<!ELEMENT carriles (#PCDATA)>



<!ATTLIST retencion long CDATA #REQUIRED>
<!ATTLIST evento
 tipo CDATA #REQUIRED
 fecha CDATA #IMPLIED
 >
 <!ATTLIST carrilescortados 
 valor (1|2|3|4) #REQUIRED 
 >

 <!--
Para ello, se va a utilizar un fichero XML que debe cumplir las siguientes premisas:
1) El nodo raíz paneles dispone de uno o más elementos evento.
2) Cada elemento evento está compuesto por los siguientes elementos obligatorios: via, pk, retencion y sentido. Además, contiene un elemento carrilescortados que es optativo.
3) El elemento evento dispone de dos atributos: tipo (obligatorio) y fecha (optativo).
4) El elemento via está formado por los siguientes elementos: nombre, ref, origen, destino. Además, podrá contener un elemento doble o un elemento sentido. También, contendrá un elemento carriles.
5) El elemento doble será un elemento vacío.
6) El elemento sentido contendrá una cadena de texto.
7) El elemento retencion es un elemento vacío que contiene un atributo long.
8) El elemento carrilescortados tendrá un atributo obligatorio denominado valor el cual solo podrá tener los valores 1, 2, 3 y 4.

Elabora un documento XML a modo de ejemplo, el cual incluya un DTD interno que permita validar la correcta estructura del fichero XML.
-->

=== DavidRodriguezLeiras/LXMI/Ejercicios UD4/tarea recopilatorio/405_Autopista - Hecho/autopista.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE paneles SYSTEM "paneles.dtd">
<paneles>
    <evento tipo="a" fecha="a">
        <via>
            <nombre>a</nombre>
            <ref>a</ref>
            <origen>a</origen>
            <destino>a</destino>
            <doble/>
            <carriles>a</carriles>
        </via>
        <pk>a</pk>
        <retencion long="a">a</retencion>
        <sentido>a</sentido>
        <carrilescortados valor="1">a</carrilescortados>
    </evento>
</paneles>
