=== DavidRodriguezLeiras/LXMI/Ejercicios UD4/tarea3_DavidRodriguezLeiras/Ejercicio2/ejercicio2.dtd
<!ELEMENT mensaje (de,para+,asunto+,adjunto+)>
    <!ELEMENT de (#PCDATA)>
    <!ELEMENT para (#PCDATA)>
    <!ELEMENT asunto (#PCDATA)>
    <!ELEMENT adjunto (#PCDATA)>

=== DavidRodriguezLeiras/LXMI/Ejercicios UD4/tarea3_DavidRodriguezLeiras/Ejercicio2/ejercicio2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE mensaje SYSTEM "ejercicio2.dtd">
<mensaje>
	<de>maria@gmail.com</de>
	<para>ignacio@gmail.com</para>
	<para>pedro@edu.xunta.es</para>
	<asunto>Env√≠oche os arquivos</asunto>
	<adjunto>D:\fotos\dePesca.jpg</adjunto>
	<adjunto>D:\docs\carta.odt</adjunto>
	<adjunto>D:\fotos\naCea.jpg</adjunto>
</mensaje>
