<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE panel [
    <!ELEMENT panel (aeropuerto,vuelo)+>
    <!ELEMENT aeropuerto (#PCDATA)>
    <!ELEMENT vuelo (diario,origen,destino,hora_salida,hora_llegada)>
    <!ELEMENT diario (#PCDATA) >
    <!ELEMENT origen (#PCDATA)>
    <!ELEMENT destino (#PCDATA)>
    <!ELEMENT hora_salida (#PCDATA)>
    <!ELEMENT hora_llegada (#PCDATA)>
    <!ATTLIST vuelo 
        codigo ID #REQUIRED
        estado (C|E|R) "E"    
    >
]>

<panel>
    <aeropuerto>Aeropuerto JFK</aeropuerto>
    <vuelo codigo="V22" estado="R">
        <diario>SI</diario>
        <origen>New York</origen>
        <destino>Chicago</destino>
        <hora_salida>9:30</hora_salida>
        <hora_llegada>11:30</hora_llegada>
    </vuelo>
    <aeropuerto>Aeropuerto JFK</aeropuerto>
    <vuelo codigo="V23" estado="C">
        <diario>NO</diario>
        <origen>New York</origen>
        <destino>Miami</destino>
        <hora_salida>10:15</hora_salida>
        <hora_llegada>11:15</hora_llegada>
    </vuelo>
</panel>